<?php

namespace Tests\Unit;

use App\Models\Category;
use App\Models\Genre;
use App\Models\Traits\Uuid;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use PHPUnit\Framework\TestCase;

class CategoryTest extends TestCase
{
    use DatabaseMigrations;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testIfUseTraits()
    {
        Genre::create(['name' => 'teste']);
        $traits = [
            SoftDeletes::class, Uuid::class
        ];
        $categoryTrait = array_keys(class_uses(Category::class));
        $this->assertEquals($traits, $categoryTrait);
        //print_r(class_uses(Category::class));
    }

    public function testFillableAttribute()
    {

        $fillable = ['name', 'description', 'is_active'];
        $category = new Category();
        $this->assertEquals($fillable, $category->getFillable());
    }

    public function testCastAttribute()
    {
        $cast = ['id' => 'string'];
        $category = new Category();
        $this->assertEquals($cast, $category->getCasts());
    }

    public function testIncrementingAttribute()
    {
        $category = new Category();
        $this->assertFalse($category->incrementing);
    }

    public function testDatesAttribute()
    {
        $dates = ['deleted_at', 'created_at', 'updated_at'];
        $category = new Category();
        foreach ($dates as $date) {
            $this->assertContains($date, $category->getDates());
        }
        $this->assertCount(count($dates), $category->getDates());
    }
}
